name: React CI

on:
  push:
    branches:
    - "main"

jobs:
  build:
    runs-on: ubuntu-latest

strategy:
  matrix:
    node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm run build
    - run: npm test
